### ISSUE TITLE
Survey Bioinfo

### ISSUE THREAD

**Issue by Alema91** [BU-ISCIII/BU-ISCIII#12]

**Comment by saramonzon** [comment]
needs revision!

**Comment by Alema91** [comment]
Revision done. Parse the survey to Google forms and check english and descriptions.

**Comment by Alema91** [comment]
Created sheet model to transform in Google Docs. Need revision of the performance [LINK](https://docs.google.com/spreadsheets/d/1RW3umhU_TvuIgZeLTIeqKXb5akxElojibhxDPlXUiEA/edit#gid=1028091160)

**Comment by Alema91** [comment]
New version. Need revision. [LINK](https://docs.google.com/forms/d/1Rnn4P__ceWn4riCNIx9y4N4ufGyH5dQ51hDsaafICIc/edit)

**Comment by Alema91** [comment]
New version. Changes has to be done. (LINK)[https://docs.google.com/spreadsheets/d/1RW3umhU_TvuIgZeLTIeqKXb5akxElojibhxDPlXUiEA/edit#gid=1028091160]

**Comment by Alema91** [comment]
Revision made. [Bioinfo survey v1.1](https://docs.google.com/forms/d/1Rnn4P__ceWn4riCNIx9y4N4ufGyH5dQ51hDsaafICIc/edit)

**Comment by Alema91** [comment]
Needed vocabulary revision.

**Comment by Alema91** [comment]
[Bioinfo survey 1.2](https://docs.google.com/forms/d/1Rnn4P__ceWn4riCNIx9y4N4ufGyH5dQ51hDsaafICIc/edit). Minor changes in English vocabulary and arrange some phrases. It might be good someone answers the survey previously for control.

**Comment by Alema91** [comment]
Sended!
