### ISSUE TITLE
Resolution for bioinfo meeting

### ISSUE THREAD

**Issue by Alema91** [BU-ISCIII/BU-ISCIII#35]

**Comment by Alema91** [comment]
Email:

Buenas tardes a todxs,

Antes de nada, muchas gracias por haber contestado al Doodle y hacernos llegar vuestras preferencias. Por lo tanto, quedaría fijada la reunión de bioinformáticos del proyecto Relecov para el día jueves 5 de mayo de 12:00 a 13:30. Os haremos llegar a lo largo de estas semanas el enlace para la reunión y más información acerca de la organización del evento.

De nuevo muchas gracias por vuestra colaboración y nos vemos en mayo.

Un saludo,

**Comment by Alema91** [comment]
Done!

**Comment by Alema91** [comment]
Send next week URL with Zoom invitation

**Comment by saramonzon** [comment]
@Alema91 esto importante, @icuesta  va a hacer la agenda y el link de zoom, estate pendiente porque hay que enviar esto hoy.

**Comment by Alema91** [comment]
Agenda: https://docs.google.com/document/d/1LUhSFhVGjJ_7dbhItOQsGlf1YAl4gUj7c3L_eruHNWs/edit

No se si falta algo más. Le pido ahora el enlace de zoom a @icuesta y cuando me digais lo envio.

**Comment by Alema91** [comment]
Zoom link included!
