### ISSUE TITLE
Plan sftp organization for uploading sequences by the network

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/BU-ISCIII#8]

**Comment by Alema91** [comment]
Create the id by laboratory acronyms and explain into excel file.

**Comment by Alema91** [comment]
Create a script to upload/download lab reference directories from sFTP

**Comment by Alema91** [comment]
Done!

Reference Lab ID: **COD_2129** / **COD-2129-MAD-BU-ISCIII**

QC directory (Survey, explanatio, contact list): [LINK](https://drive.google.com/drive/folders/14M5nlCOrLp7qLF2eVzE9yJGMyikRF7R5)

**Comment by Alema91** [comment]
Done!

Reference Lab ID: **COD_2129** / **COD-2129-MAD-BU-ISCIII**

QC directory (Survey, explanatio, contact list): [LINK](https://drive.google.com/drive/folders/14M5nlCOrLp7qLF2eVzE9yJGMyikRF7R5)
